files:
  - source: /book/website/
    ignore_settings: 1
    ignore:
      - LICENSE.md
      - _toc.yml
      - _config.yml
      - _redirects
      - requirements.txt
      - *.jpg
      - *.png
      - runtime.txt
    translation: /book/translation/%three_letters_code%/%original_path%/%original_file_name%
