files:
  - source: /book/website/
    ignore:
      - '*.jpg'
      - '*.yml'
      - '*.css'
      - '*.js'
      - _redirects
      - '*.txt'
      - LICENSE.md
    translation: /book/website/translation/%language%/%original_file_name%
